billboardsite/billboard/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('announcements/', AnnouncementList.as_view(), name='announcement_list'),
    path('announcements/<int:pk>', AnnouncementDetail.as_view(), name='announcement_detail'),
    path('announcements/create', AnnouncementCreate.as_view(), name='announcement_create'),
    path('announcements/<int:pk>/edit', AnnouncementUpdate.as_view(), name='announcement_edit'),
    path('announcements/<int:pk>/delete', AnnouncementDelete.as_view(), name='announcement_delete'),
    path("announcements/search", AnnouncementSearch.as_view(), name="announcement_search"),

    path('category/<int:pk>', CategoryListView.as_view(), name='announcement_by_category'),

    path('replies/<int:pk>/approve', reply_approve, name='reply_approve'),
    path('replies/<int:pk>/declain', reply_declain, name='reply_declain'),
    path('replies/<int:pk>/reset', reply_reset, name='reply_reset'),
    path('replies/my', ReplyMyList.as_view(), name='reply_my_list'),
    path('replies/forme', AnnWithReplyForMeList.as_view(), name='reply_forme_list'),
    path('replies/<int:pk>/delete', ReplyDelete.as_view(), name='reply_delete'),

    path('newsletters/', NewsLetterList.as_view(), name='newsletter_list'),
    path('newsletters/<int:pk>', NewsLetterDetail.as_view(), name='newsletter_detail'),
    path('newsletters/create', NewsLetterCreate.as_view(), name='newsletter_create'),
    path('newsletters/<int:pk>/edit', NewsLetterUpdate.as_view(), name='newsletter_edit'),
    path('newsletters/<int:pk>/delete', NewsLetterDelete.as_view(), name='newsletter_delete'),
    path('newsletters/reqtonewsauthors', request_to_newsauthors, name='request_to_newsauthors'),
    path('newsletters/addtonewsauthors/<int:user_id>', add_to_newsauthors, name='add_to_newsauthors'),
    path('newsletters/declaintonewsauthors/<int:user_id>', declain_to_newsauthors, name='declain_to_newsauthors'),

    path('userprofile/<int:pk>', UserProfileUpdate.as_view(), name='userprofile_edit'),

    path('customconfirmation/', confirmationproccessing, name='confirmationproccessing')
]

billboardsite/billboardsite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from billboardsite import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('billboard/', include('billboard.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    # urlpatterns += [
    #     path('__debug__/', include('debug_toolbar.urls')),
    # ]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

billboardsite/billboard/models.py
import pytz as pytz

from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator, RegexValidator
from django.db import models
from django.db.models import F
from django.urls import reverse

from ckeditor_uploader.fields import RichTextUploadingField


TIMEZONES = list(zip(pytz.all_timezones, pytz.all_timezones))


class Announcement(models.Model):
    title = models.CharField(max_length=254,
                             unique=True,
                             error_messages={'unique': 'Такое объявление уже есть'},
                             db_index=True,
                             verbose_name='Заголовок')
    content = RichTextUploadingField(validators=[MinLengthValidator(4)],
                                     verbose_name='Содержание')
    photoimage = models.ImageField(upload_to='photoannouncement/',
                                   blank=True,
                                   default='photoannouncement/photoannouncement_default.jpg',
                                   verbose_name='Миниатюра объявления',
                                   )
    is_published = models.BooleanField(default=True,
                                       verbose_name='Публикация')
    time_create = models.DateTimeField(auto_now_add=True,
                                       verbose_name='Дата создания')
    time_update = models.DateTimeField(auto_now=True,
                                       verbose_name='Дата редактирования')
    category = models.ForeignKey(to='Category',
                                 on_delete=models.CASCADE,
                                 related_name='cat_announcements',
                                 verbose_name='Категория')
    author_ann = models.ForeignKey(to=User,
                                   on_delete=models.CASCADE,
                                   related_name='auth_announcements',
                                   verbose_name='Автор объявлений')

    num_replies = models.IntegerField(default=0, verbose_name='Количество откликов')

    pageviews = models.PositiveBigIntegerField(default=0, verbose_name='Количество просмотров')

    def __str__(self):
        return f'{self.title}'

    def announcement_preview(self):
        return f'{self.title[:40]}...'

    def pageviews_plus(self):
        self.__class__.objects.update(pageviews=F('pageviews') + 1)
        return self.pageviews

    def count_replies(self):
        replies_num = self.replies.all().count()
        self.num_replies = replies_num
        self.save()
        return replies_num

    def get_absolute_url(self):
        return reverse('announcement_detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'Объявления'
        verbose_name_plural = 'Объявления'


class Category(models.Model):
    catname = models.CharField(max_length=64,
                               unique=True,
                               verbose_name='Категория')

    slug = models.SlugField(max_length=64,
                            unique=True,
                            db_index=True,
                            verbose_name='URL',
                            null=True)

    def __str__(self):
        return f'{self.catname}'

    @property
    def published_cat_ann(self):
        return self.cat_announcements.all().filter(is_published=True).count()

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Reply(models.Model):
    APPROVE_STATUS = [
        ('approved', 'Принят'),
        ('declained', 'Отклонен'),
        ('no_status', 'Без статуса')
    ]

    announcement = models.ForeignKey(to=Announcement,
                                     related_name='replies',
                                     on_delete=models.CASCADE)
    content = models.TextField(validators=[MinLengthValidator(4)],
                               verbose_name='Содержание')
    time_create = models.DateTimeField(auto_now_add=True,
                                       verbose_name='Дата создания')
    time_update = models.DateTimeField(auto_now=True,
                                       verbose_name='Дата редактирования')
    is_approved = models.CharField(max_length=16,
                                   choices=APPROVE_STATUS,
                                   default='no_status',
                                   verbose_name='Одобрение'
                                   )
    author_repl = models.ForeignKey(to=User,
                                    on_delete=models.CASCADE,
                                    related_name='auth_replies',
                                    verbose_name='Автор отликов')

    def __str__(self):
        return f'{self.content[:15]}...'

    def reply_preview(self):
        return f'{self.content[:40]}...'

    class Meta:
        verbose_name = 'Отлик'
        verbose_name_plural = 'Отлики'


class Newsletter(models.Model):
    title = models.CharField(max_length=254,
                             unique=True,
                             error_messages={'unique': 'Новость с таким заголовком уже есть'},
                             db_index=True,
                             verbose_name='Заголовок')
    content = models.TextField(validators=[MinLengthValidator(4)],
                               verbose_name='Содержание(текст)')
    photoimage = models.ImageField(upload_to='photonewsletter/',
                                   default='photonewsletter/photonewsletter_default.jpg',
                                   )
    category = models.ForeignKey(to='Category',
                                 on_delete=models.CASCADE,
                                 related_name='cat_newsletters',
                                 verbose_name='Категория')
    is_published = models.BooleanField(default=True,
                                       verbose_name='Готовность')
    is_sent = models.BooleanField(default=False,
                                  verbose_name='Отправлено')
    time_create = models.DateTimeField(auto_now_add=True,
                                       verbose_name='Дата создания')
    author_news = models.ForeignKey(to=User,
                                    on_delete=models.CASCADE,
                                    related_name='auth_newsletters',
                                    verbose_name='Автор новостей')
    pageviews = models.PositiveBigIntegerField(default=0, verbose_name='Количество просмотров')

    def __str__(self):
        return f'{self.title}'

    def newsletter_preview(self):
        return f'{self.title[:120]}...'

    def pageviews_plus(self):
        self.__class__.objects.update(pageviews=F('pageviews') + 1)
        return self.pageviews

    def get_absolute_url(self):
        return reverse('newsletter_list')

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'


class UserProfile(models.Model):
    user = models.OneToOneField(User,
                                on_delete=models.CASCADE,
                                primary_key=True,
                                )
    nickname = models.CharField(max_length=16,
                                unique=True,
                                error_messages={'unique': 'Никнейм занят'},
                                blank=False,
                                validators=[RegexValidator(r'^[a-zA-Z]+[0-9a-zA-Z]*$',
                                                           'Никнейм должен быть буквенно-цифровым и начинаться с букву')
                                            ],
                                help_text='Никнейм должен быть буквенно-цифровым и начинаться с букву',
                                verbose_name='Никнейм',
                                )
    photoimage = models.ImageField(upload_to='photoprofile/',
                                   default='photoprofile/photoprofile_default.jpg',
                                   )
    aboutme = models.CharField(max_length=1024,
                               blank=True,
                               verbose_name='Описание',
                               )
    timezone = models.CharField(max_length=64,
                                choices=TIMEZONES,
                                default='UTC',
                                verbose_name='Timezone',
                                )
    is_replies_alerts = models.BooleanField(default=True,
                                            verbose_name='Оповещение о новых отликах')
    appr_replies_alerts = models.BooleanField(default=True,
                                              verbose_name='Оповещение о принятии отлика')
    is_news_subscribe = models.BooleanField(default=True,
                                            verbose_name='Подписка на новостную рассылку')

    def __str__(self):
        return f'{self.user.username}Profile'

    class Meta:
        verbose_name = 'Профиль пользователя'
        verbose_name_plural = 'Профиль пользователя'

billboardsite/billboard/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.db.models.fields.files import ImageFieldFile

from billboardsite.settings import IMAGE_ALLOWED_FORMATS, IMAGE_MIN_SIZE
from .custom_forms import CommonForm
from .models import Announcement, Reply, Newsletter, UserProfile
from .utils import check_resize_image


class AnnouncementForm(CommonForm):

    class Meta:
        model = Announcement
        fields = ['title', 'photoimage', 'content', 'is_published', 'category']


class NewsLetterForm(CommonForm):

    class Meta:
        model = Newsletter
        fields = ['title', 'photoimage', 'content', 'is_published', 'category']


class ReplyForm(forms.ModelForm):
    content = forms.CharField(min_length=4,
                              label='Текст отлика',
                              widget=forms.Textarea(attrs={'placeholder': 'Введите текст отклика',
                                                           'rows': '4',
                                                           'cols': '85%'
                                                           }
                                                    )
                              )

    class Meta:
        model = Reply
        fields = ['content']


class UserProfileForm(forms.ModelForm):

    allowed_formats_ = ', '.join(IMAGE_ALLOWED_FORMATS).replace('image/', '.')
    min_size_ = '*'.join(map(str, IMAGE_MIN_SIZE))

    photoimage = forms.ImageField(help_text='Поддерживаемые форматы: {allowed_formats}. \n'
                                            'Минимальное разрешение: {min_size}.'.format(allowed_formats=allowed_formats_, min_size=min_size_),
                                  error_messages={'invalid_image': 'Загрузите изображение повторно. '
                                                  'Загруженный вами файл либо не был изображением, либо был поврежден.'},
                                  )

    class Meta:
        model = UserProfile
        fields = ['nickname', 'photoimage', 'aboutme', 'timezone', 'is_replies_alerts', 'appr_replies_alerts', 'is_news_subscribe']
        widgets = {
            'aboutme': forms.Textarea(attrs={'placeholder': 'Немного о себе...',
                                             'rows': '2',
                                             'cols': '85%'
                                             }),
        },
        labels = {
            'nickname': 'Никнейм:',
            'aboutme': 'Немного о себе:',
            'timezone': 'Часовой пояс:',
        }

    def clean_photoimage(self):
        upl_photo = self.cleaned_data['photoimage']
        if not isinstance(upl_photo, ImageFieldFile):  # Если поле в POST пустое, то тип ImageFieldFile
            if upl_photo.content_type in IMAGE_ALLOWED_FORMATS and \
                    (upl_photo.image.size[0] >= 150 and upl_photo.image.size[1] >= 150):
                upl_photo_ = check_resize_image(upl_photo,
                                                self.instance.user,
                                                IMAGE_MIN_SIZE
                                                )
                return upl_photo_
            raise ValidationError(message='Ошибка загрузки: Неверный формат изображения или маленькое разрешение')

    # def clean_timezone(self):
    #     timezone = self.cleaned_data['timezone']
    #     self.request.session["django_timezone"] = request.POST["timezone"]
    #     print(timezone)
    #     return timezone

billboardsite/billboard/templates/billboard/announcement_delete.html
{% extends 'flatpages/base.html' %}

{% load static %}
{% load custom_tags %}

{% block title %}
    Удаление объявления
{% endblock title %}

{% block category %}
    {% tag_categories_block %}
{% endblock category %}

{% block announcement %}
    <div class="col-md-12">
        <h1 class="mb-2">Удаление объявления «{{ object|truncatechars:40 }}»</h1>
    </div>

    <form method="post">{% csrf_token %}
        <p>Вы действительно хотите удалить объявление?</p>
        {{ form }}
        <p class="form-buttons">
			<input type="submit" class="btn btn-outline-danger" value="Удалить">
			<a href="{% url 'announcement_detail' object.pk %}" class="btn btn-secondary">Отмена</a>
		</p>
    </form>

{% endblock announcement %}

billboardsite/billboard/templates/billboard/announcement_edit.html
{% extends 'flatpages/base.html' %}

{% load static %}
{% load custom_tags %}

{% block title %}
    Редактирование объявления
{% endblock title %}

{% block category %}
    {% tag_categories_block %}
{% endblock category %}

{% block announcement %}
<style>
.miniature-image {
    width: 130px;
    height: 130px;
    margin-bottom: 10px;
}
</style>

    <div class="col-md-12">
        <h1 class="mb-2">Редактирование объявления</h1>
    </div>


<div class="container mt-5">

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media}}
            <div class="form-error">{{ form.non_field_errors }}</div>
            <div class="form-group">
                <div><label for="{{ form.title.id_for_label }}" class="text-dark">{{ form.title.label }}</label></div>
                {{ form.title }}
                <div class="form-error">{{ form.title.errors }}</div>
            </div>
            <label for="id_photoimage">Текущая миниатюра объявления:</label>
            <div class="media">
                <img id="id_photoimage" class="rounded-circle miniature-image" src="{{ object.photoimage.url }}" alt="Miniature_photo">
            </div>
            <div class="form-group">
                <input type="file" name="photoimage" accept=".jpg, .jpeg, .png"/>
                {% if form.photoimage.errors %}
                <div class="form-error">{{ form.photoimage.errors }}</div>
                {% else %}
                <small class="form-text text-muted">{{ form.photoimage.help_text }}</small>
                {% endif %}
            </div>
            <div class="form-group">
                <div><label for="{{ form.content.id_for_label }}" class="text-dark">{{ form.content.label }}</label></div>
                {{ form.content }}
                <div class="form-error">{{ form.content.errors }}</div>
            </div>
            <div class="form-group">
                <div><label for="{{ form.is_published.id_for_label }}" class="text-dark">{{ form.is_published.label }}</label></div>
                {{ form.is_published }}
                <div class="form-error">{{ form.is_published.errors }}</div>
            </div>
            <div class="form-group">
                <div><label for="{{ form.category.id_for_label }}" class="text-dark">{{ form.category.label }}</label></div>
                {{ form.category }}
                <div class="form-error">{{ form.category.errors }}</div>
            </div>
            <div class="row justify-content-center">
                <input type="submit" class="btn btn-success" style="margin-bottom: 10px" value="Изменить" />
                <a href="{% url 'announcement_detail' object.pk %}" class="btn btn-outline-secondary">Отмена</a>
            </div>
        </form>
</div>

{% endblock announcement %}

billboardsite/billboard/templates/billboard/announcement_list.html
{% extends 'flatpages/base.html' %}

{% load static %}
{% load custom_tags %}

{% block title %}
    Все объявления
{% endblock title %}

{% block category %}
    {% tag_categories_block %}
{% endblock category %}

{% block announcement %}

    {% for announcement in all_announcement %}
			    			<div class="col-md-12">
									<div class="blog-entry ftco-animate d-md-flex">
                                        <a href="{% url 'announcement_detail' pk=announcement.pk %}" class="img img-2" style="background-image: url({{ announcement.photoimage.url }});"></a>
										<div class="text text-2 pl-md-4">
				              <h3 class="mb-2"><a href="{% url 'announcement_detail' pk=announcement.pk %}">{{ announcement.title }}</a></h3>
                            <div class="meta-wrap">
                                  <p class="meta" style="margin-bottom: 0rem">
                                    <span><i class="icon-face mr-1"></i>Автор: {{ announcement.ann_nickname }}</span>
                                    <span><i class="icon-calendar mr-1"></i>Обновлено: {{ announcement.time_update|date:'d.m.y H:i' }}</span>
                                    <span><a href="{% url 'announcement_by_category' pk=announcement.category.pk  %}"><i class="icon-folder-o mr-1"></i>{{ announcement.category }}</a></span>
				              		<span><i class="icon-comment2 mr-1" title="Отлики"></i>{{ announcement.num_replies }}</span>
				              	    <span><i class="icon-eye" title="Просмотры"></i>&nbsp;{{ announcement.pageviews }}</span>
                                  </p>
			              	</div>
				              <p class="mb-4">{{ announcement.content|striptags|safe|truncatechars:100 }}</p>
				              <p><a href="{% url 'announcement_detail' pk=announcement.pk %}" class="btn-custom">Подробнее <span class="ion-ios-arrow-forward"></span></a></p>
				            </div>
									</div>
								</div>
    {% empty %}
        <div class="col-md-12">
            <div class="blog-entry ftco-animate d-md-flex">
                <div class="text text-2 pl-md-4">
                    <h3 class="mb-2">Таких объявлений нет.</h3>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock announcement %}

{% block lastnewsletters %}
    {% tags_lastnewsletters_block %}
{% endblock lastnewsletters %}


{% block searchbox %}

    <div class="sidebar-box pt-md-4">
      <form action="#" class="search-form" method="get">
        <div class="form-group">
            {{ filtered_queryset.form.title }}
        </div>
      {% if request.user.is_authenticated %}
        <div style="margin-top: 30px; font-size: 14px;">
            <p><label class="form-label" for="{{ filtered_queryset.form.is_author_ann.id_for_label }}">Мои объявления: </label> &nbsp;
                {{ filtered_queryset.form.is_author_ann }}
            </p>
        </div>
      {% endif %}
      </form>
    </div>
{% endblock searchbox %}

billboardsite/billboard/templates/billboard/newsletter_create.html
{% extends 'flatpages/base_wide.html' %}

{% load static %}
{% load custom_tags %}

{% block title %}
    Создание новости для рассылки
{% endblock title %}


{% block announcement %}
    <div class="col-md-12">
        <h1 class="mb-2">Создание новости для рассылки</h1>
    </div>

<div class="container mt-5">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media}}
            <div class="form-error">{{ form.non_field_errors }}</div>
            {% for field in form %}
            <div class="form-group">
                <div><label for="{{ field.id_for_label }}" class="text-dark">{{ field.label }}: </label></div>
                {{ field }}
                <div class="form-error">{{ field.errors }}</div>
            </div>
            {% endfor %}
            <div class="row justify-content-center">
                <input type="submit" class="btn btn-info" style="margin-bottom: 10px" value="Создать" />
                <a href="{% url 'newsletter_list' %}" class="btn btn-outline-secondary">Отмена</a>
            </div>
        </form>
</div>

{% endblock announcement %}

billboardsite/billboard/templates/billboard/newsletter_delete.html
{% extends 'flatpages/base_wide.html' %}

{% load static %}
{% load custom_tags %}

{% block title %}
    Удаление новости для рассылки
{% endblock title %}

{% block announcement %}
    <div class="col-md-12">
        <h1 class="mb-2">Удаление новости для рассылки «{{ object|truncatechars:40 }}»</h1>
    </div>

    <form method="post">{% csrf_token %}
        <p>Вы действительно хотите удалить новость?</p>
        {{ form }}
        <p class="form-buttons">
			<input type="submit" class="btn btn-outline-danger" value="Удалить">
			<a href="{% url 'newsletter_detail' object.pk %}" class="btn btn-secondary">Отмена</a>
            <a href="{% url 'newsletter_edit' object.pk %}" class="btn btn-outline-primary">Редактировать</a>
		</p>
    </form>

{% endblock announcement %}

billboardsite/billboard/templates/billboard/newsletter_edit.html
{% extends 'flatpages/base_wide.html' %}

{% load static %}
{% load custom_tags %}

{% block title %}
    Редактирование новости для рассылки
{% endblock title %}

{% block category %}
    {% tag_categories_block %}
{% endblock category %}

{% block announcement %}
<style>
.miniature-image {
    width: 130px;
    height: 130px;
    margin-bottom: 10px;
}
</style>


    <div class="col-md-12">
        <h1 class="mb-2">Редактирование новости для рассылки</h1>
    </div>


<div class="container mt-5">

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media}}
            <div class="form-error">{{ form.non_field_errors }}</div>
            <div class="form-group">
                <div><label for="{{ form.title.id_for_label }}" class="text-dark">{{ form.title.label }}</label></div>
                {{ form.title }}
                <div class="form-error">{{ form.title.errors }}</div>
            </div>
            <label for="id_photoimage">Текущая миниатюра объявления:</label>
            <div class="media">
                <img id="id_photoimage" class="rounded-circle miniature-image" src="{{ object.photoimage.url }}" alt="Miniature_photo">
            </div>
            <div class="form-group">
                <input type="file" name="photoimage" accept=".jpg, .jpeg, .png"/>
                {% if form.photoimage.errors %}
                <div class="form-error">{{ form.photoimage.errors }}</div>
                {% else %}
                <small class="form-text text-muted">{{ form.photoimage.help_text }}</small>
                {% endif %}
            </div>
            <div class="form-group">
                <div><label for="{{ form.content.id_for_label }}" class="text-dark">{{ form.content.label }}</label></div>
                {{ form.content }}
                <div class="form-error">{{ form.content.errors }}</div>
            </div>
            <div class="form-group">
                <div><label for="{{ form.is_published.id_for_label }}" class="text-dark">{{ form.is_published.label }}</label></div>
                {{ form.is_published }}
                <div class="form-error">{{ form.is_published.errors }}</div>
            </div>
            <div class="form-group">
                <div><label for="{{ form.category.id_for_label }}" class="text-dark">{{ form.category.label }}</label></div>
                {{ form.category }}
                <div class="form-error">{{ form.category.errors }}</div>
            </div>
            <div class="row justify-content-center">
                <input type="submit" class="btn btn-success" style="margin-bottom: 10px" value="Изменить" />
                <a href="{% url 'newsletter_list' %}" class="btn btn-outline-secondary">Отмена</a>
            </div>
        </form>
</div>

{% endblock announcement %}

billboardsite/billboard/templates/billboard/reply_delete.html
{% extends 'flatpages/base.html' %}

{% load static %}
{% load custom_tags %}

{% block title %}
    Удаление отлика
{% endblock title %}

{% block category %}
    {% tag_categories_block %}
{% endblock category %}

{% block announcement %}
    <div class="col-md-12">
        <h1 class="mb-2">Удаление отлика «{{ object|truncatechars:40 }}»</h1>
    </div>

    <form method="post">{% csrf_token %}
        <p>Вы действительно хотите удалить отлик?</p>
        {{ form }}
        <p class="form-buttons">
			<input type="submit" class="btn btn-outline-danger btn-sm" value="Удалить">
			<a href="{% url 'announcement_detail' object.announcement.pk %}" class="btn btn-primary btn-sm">Отмена</a>
		</p>
    </form>

{% endblock announcement %}

billboardsite/billboard/templates/billboard/userprofile_edit.html
{% extends 'flatpages/base.html' %}

{% load static %}
{% load custom_tags %}
{% load custom_filters %}

{% load crispy_forms_tags %}

{% block category %}
    {% tag_categories_block %}
{% endblock category %}


{% block announcement %}
<style>

.form-group {
    margin-bottom: 0.7rem;
}

.form-control {
    height: 35px !important;
    width: 100%;
    background: #fff !important;
    color: #000000 !important;
    font-size: 13px;
    border-radius: 0px;
    -webkit-box-shadow: none !important;
    box-shadow: none !important;
}

.form-control:focus, .form-control:active {
    border-color: #94e80e;
}

.form-check-label {
    margin-bottom: 0;
    font-size: 13px;
}

.miniature-image {
    width: 130px;
    height: 130px;
    margin-bottom: 10px;
}

</style>


    <div class="col-md-12">
        <h1 class="mb-2">Мои профиль</h1>
    </div>


<div class="container mt-5">
        <label for="id_photoimage">Ваш текущий аватар:</label>
        <div class="media">
            <img id="id_photoimage" class="rounded-circle miniature-image" src="{{ object.photoimage.url }}" alt="Avatar_photo">
        </div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media}}
                <div class="form-error">{{ form.non_field_errors }}</div>
                <div class="form-group">
                    <input type="file" name="photoimage" accept=".jpg, .jpeg, .png"/>
                    {% if form.photoimage.errors %}
                    <div class="form-error">{{ form.photoimage.errors }}</div>
                    {% else %}
                    <small class="form-text text-muted">{{ form.photoimage.help_text }}</small>
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.nickname|as_crispy_field }}
                    <div class="form-error">{{ form.nickname.errors }}</div>
                </div>
                <div class="form-group">
                    {{ form.aboutme|as_crispy_field }}
                    <div class="form-error">{{ form.aboutme.errors }}</div>
                </div>
                <div class="form-group">
                    {{ form.timezone|as_crispy_field }}
                    <div class="form-error">{{ form.timezone.errors }}</div>
                </div>
                <div class="form-group">
                    {{ form.is_replies_alerts|as_crispy_field }}
                    <div class="form-error">{{ form.is_replies_alerts.errors }}</div>
                </div>
                <div class="form-group">
                    {{ form.appr_replies_alerts|as_crispy_field }}
                    <div class="form-error">{{ form.appr_replies_alerts.errors }}</div>
                </div>
                <div class="form-group">
                    {{ form.is_news_subscribe|as_crispy_field }}
                    <div class="form-error">{{ form.is_news_subscribe.errors }}</div>
                </div>

            <div>
                {% if messages %}
                        {% for message in messages %}
                         <p><i class="icon-info-circle">&nbsp; {{ message }}</i></p>
                        {% endfor %}
                {% endif %}
            </div>

            <input type="submit" class="btn btn-success" value="Применить"/>
            <hr>
            {% if not perms.billboard.add_newsletter %}
                Хочу тоже публиковать интересные новости! <a href="{% url 'request_to_newsauthors' %}">Отправить запрос администраторам.</a>
            {% endif %}
            &nbsp;
        </form>

</div>

{% endblock announcement %}

{% block lastnewsletters %}
    {% tags_lastnewsletters_block %}
{% endblock lastnewsletters %}